steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/talentsecure-frontend:$COMMIT_SHA'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/talentsecure-frontend:$COMMIT_SHA'
    id: 'push-image'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talentsecure-frontend'
      - '--image'
      - 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/talentsecure-frontend:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-service'

images:
  - 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/talentsecure-frontend:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
